"""empty message

Revision ID: 0d490cbf5c7c
Revises: 
Create Date: 2022-08-15 15:39:27.981630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d490cbf5c7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('res_id', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(length=100), nullable=False),
    sa.Column('opr_name', sa.String(length=10), nullable=False),
    sa.Column('opr_code', sa.String(length=10), nullable=False),
    sa.Column('bkg_ref', sa.String(length=100), nullable=False),
    sa.Column('guest_name', sa.String(length=100), nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('sales_date', sa.DateTime(), nullable=False),
    sa.Column('in_date', sa.DateTime(), nullable=False),
    sa.Column('out_date', sa.DateTime(), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=False),
    sa.Column('meal', sa.String(length=24), nullable=False),
    sa.Column('days', sa.SmallInteger(), nullable=False),
    sa.Column('adult', sa.SmallInteger(), nullable=False),
    sa.Column('child', sa.SmallInteger(), nullable=False),
    sa.Column('purchase', sa.Float(), nullable=False),
    sa.Column('sales', sa.Float(), nullable=False),
    sa.Column('opr_cost', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('statu4', sa.String(length=10), nullable=False),
    sa.Column('gwg_p_id', sa.Integer(), nullable=False),
    sa.Column('gwg_p_name', sa.String(length=100), nullable=False),
    sa.Column('gwg_p_code', sa.String(length=100), nullable=False),
    sa.Column('gwg_s_id', sa.Integer(), nullable=False),
    sa.Column('gwg_s_name', sa.String(length=100), nullable=False),
    sa.Column('gwg_s_code', sa.String(length=100), nullable=False),
    sa.Column('status_id', sa.Integer(), server_default=sa.text('-1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('GETUTCDATE()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('GETUTCDATE()'), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_bkg_ref'), 'booking', ['bkg_ref'], unique=False)
    op.create_index(op.f('ix_booking_hotel_name'), 'booking', ['hotel_name'], unique=False)
    op.create_index(op.f('ix_booking_import_date'), 'booking', ['import_date'], unique=False)
    op.create_index(op.f('ix_booking_in_date'), 'booking', ['in_date'], unique=False)
    op.create_index(op.f('ix_booking_opr_name'), 'booking', ['opr_name'], unique=False)
    op.create_index(op.f('ix_booking_out_date'), 'booking', ['out_date'], unique=False)
    op.create_index(op.f('ix_booking_ref_id'), 'booking', ['ref_id'], unique=False)
    op.create_index(op.f('ix_booking_res_id'), 'booking', ['res_id'], unique=False)
    op.create_index(op.f('ix_booking_sales_date'), 'booking', ['sales_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_sales_date'), table_name='booking')
    op.drop_index(op.f('ix_booking_res_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_ref_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_out_date'), table_name='booking')
    op.drop_index(op.f('ix_booking_opr_name'), table_name='booking')
    op.drop_index(op.f('ix_booking_in_date'), table_name='booking')
    op.drop_index(op.f('ix_booking_import_date'), table_name='booking')
    op.drop_index(op.f('ix_booking_hotel_name'), table_name='booking')
    op.drop_index(op.f('ix_booking_bkg_ref'), table_name='booking')
    op.drop_table('booking')
    op.drop_table('status')
    # ### end Alembic commands ###
